site_name: Jekyll Template Documentation



theme:
  name: material
  palette:
    scheme: slate


markdown_extensions:
  - admonition
  - codehilite


repo_name: djgoldsmith/JekyllTemplate
repo_url: https://github.com/JekyllTemplate



nav:
  - Home: index.md
  - Tutorial:
    - Introduction: introduction.md
    - Getting Started: gettingStarted.md
    - Adding Content: addingContent.md
  - Advanced:
    - Working Locally: localInstall.md

